version: '3'

services:
  database:
    container_name: database
    image: postgres:13.4-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./redis:/var/lib/redis

  bot:
    container_name: bot
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
    environment:
      RUN_MIGRATIONS: 'true'
      DOCKER: 'true'
      REDIS_HOST: redis
      POSTGRES_HOST: database
    depends_on:
      - database
      - redis
