name: "CI/CD"

env:
  PROJECT_NAME: "template_bot"

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t ${{ env.PROJECT_NAME }} .
      - name: Add tags
        run: |
          docker tag ${{ env.PROJECT_NAME }} ${{ secrets.DOCKER_LOGIN }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          docker tag ${{ env.PROJECT_NAME }} ${{ secrets.DOCKER_LOGIN }}/${{ env.PROJECT_NAME }}:latest
      - name: Push to registry
        run: |
          docker push ${{ secrets.DOCKER_LOGIN }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_LOGIN }}/${{ env.PROJECT_NAME }}:latest

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: SSH to server and pull newly built image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: docker pull ${{ secrets.DOCKER_LOGIN }}/${{ env.PROJECT_NAME }}:latest
